# Generated by Django 3.1.5 on 2021-01-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_auto_20180425_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=32, verbose_name='设备名称')),
                ('schedule_date', models.DateField(verbose_name='排期日期')),
                ('using_time', models.IntegerField(choices=[(8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00')], verbose_name='占用时间')),
            ],
            options={
                'verbose_name': '设备排期管理',
                'verbose_name_plural': '设备排期管理',
                'ordering': ['-schedule_date'],
                'unique_together': {('device_name', 'using_time')},
            },
        ),
    ]
