# Generated by Django 3.1.5 on 2021-01-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_auto_20210127_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devices',
            options={'ordering': ['-device'], 'verbose_name': '设备排期管理', 'verbose_name_plural': '设备排期管理'},
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='device_name',
            new_name='device',
        ),
        migrations.AlterUniqueTogether(
            name='devices',
            unique_together={('device',)},
        ),
        migrations.RemoveField(
            model_name='devices',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='using_time',
        ),
    ]
